fix: invalid Yaml document separator: apiVersion: v1
redpanda-data/helm-charts pull request #1411
Opened 2024-07-09 13:06 UTC by maksym-iv

Apparently Terraform Helm doesn't like the notation used in the `charts/redpanda/templates/service.internal.yaml` (delimiter without condition).

Replicating the notation from `charts/redpanda/templates/poddisruptionbudget.yaml` fixed the issue.

Fixes the #1410

2024-07-09 13:53 UTC, RafalKorepta approved these changes

2024-07-09 13:53 UTC, RafalKorepta commented
@maksym-iv if you could sign CLA and bump https://github.com/redpanda-data/helm-charts/blob/d2444af416d0e182f476bb231f90d7b2b7c636d7/charts/redpanda/Chart.yaml#L26

2024-07-09 15:36 UTC, maksym-iv commented
> @maksym-iv if you could sign CLA and bump
> 
> https://github.com/redpanda-data/helm-charts/blob/d2444af416d0e182f476bb231f90d7b2b7c636d7/charts/redpanda/Chart.yaml#L26

Sure, done, lmk plz if any other change needed

2024-07-09 15:38 UTC, maksym-iv commented
> @maksym-iv if you could sign CLA and bump
> 
> https://github.com/redpanda-data/helm-charts/blob/d2444af416d0e182f476bb231f90d7b2b7c636d7/charts/redpanda/Chart.yaml#L26

Sure, done, lmk plz if anything else needed

2024-07-09 17:25 UTC, maksym-iv commented
> @maksym-iv if you could sign CLA and bump
> 
> https://github.com/redpanda-data/helm-charts/blob/d2444af416d0e182f476bb231f90d7b2b7c636d7/charts/redpanda/Chart.yaml#L26

My bad, I previously pushed with another email set in git config, force pushed with a proper one, CLA should be good now.

2024-07-10 13:35 UTC, chrisseto requested changes
Ah, real sorry to block this for a fault of my own. We've got a breaking change in main that we don't want to release until it's fixed up. 😓 

@RafalKorepta think we should revert the post_upgrade_job PR for now?

2024-07-10 13:57 UTC, chrisseto commented
You can ignore the CI failure. That'll be fixed in https://github.com/redpanda-data/helm-charts/pull/1412

I think I had to do some cheating in one of our tests to filter out empty YAML blocks. Sounds like it would be good to remove that so we can catch this issue ourselves.

2024-07-10 16:33 UTC, maksym-iv commented
> You can ignore the CI failure. That'll be fixed in #1412
> 
> I think I had to do some cheating in one of our tests to filter out empty YAML blocks. Sounds like it would be good to remove that so we can catch this issue ourselves.

Rebased from main, force pushed since #1412 seems to be merged

2024-07-10 17:36 UTC, chrisseto approved these changes
LGTM!

2024-07-10 21:05 UTC, maksym-iv commented
> LGTM!

I believe I can't merge due to CI lint failure, if you have such permissions, may you merge plz?

2024-07-10 21:21 UTC, RafalKorepta approved these changes

2024-07-10 22:09 UTC, merged