rp: add required resources to clusterrole for rpk bundle
redpanda-data/helm-charts pull request #291
Opened 2023-01-23 20:54 UTC by r-vasquez

We are introducing rpk debug bundle for k8s environments in 23.1, this functionality depends on the k8s API and it needs to be able to 'get' the listed resources of this commit.

Here is where we use them: https://github.com/redpanda-data/redpanda/blob/dev/src/go/rpk/pkg/cli/cmd/debug/bundle/bundle_k8s_linux.go#L265-L274

That means that rpk debug bundle will only work if you have `Values.rbac.enabled=true`

2023-01-24 16:53 UTC, joejulian requested changes
For auditability, I'd prefer to have these in their own clusterrole.

2023-01-24 17:33 UTC, r-vasquez commented
@joejulian Should I use the same flag (rbac.enabled) from the Values.yaml ? I guess this is something that shouldn't be enabled by default.

2023-01-24 18:44 UTC, joejulian commented
> @joejulian Should I use the same flag (rbac.enabled) from the Values.yaml ? I guess this is something that shouldn't be enabled by default.

Yes. Should we add a subtree to rbac? Maybe `rbac.rpk_debug.enable` or something like that?

2023-01-24 23:56 UTC, r-vasquez commented
Rebased and created a separate clusterrole : {redpanda.fullname}-rpk-bundle but reused the same values.rbac.enabled.

2023-01-27 00:28 UTC, joejulian approved these changes
lgtm

2023-01-27 15:29 UTC, r-vasquez commented
[Force Push 1:](https://github.com/redpanda-data/helm-charts/compare/6902fd696d2c1cbdf2e7c4003ea9974f0926f1a8..da2839f43c7c14d1024727e36ae1a94579c04765) Version Bump

[Force Push 2:](https://github.com/redpanda-data/helm-charts/compare/da2839f43c7c14d1024727e36ae1a94579c04765..63742847638fdf40363b215baa4d2ed0c5eaf51a) Rebase with main.

2023-01-27 16:57 UTC, merged