feat: make login-jwt-secret configurable
redpanda-data/helm-charts pull request #451
Opened 2023-04-20 07:38 UTC by stefan-caraiman

Required in GitOps tools such as ArgoCD https://argo-cd.readthedocs.io/en/stable/user-guide/helm/#random-data

The random value is regenerated every time the comparison is made, any application which makes use of the randAlphaNum function will always be in an OutOfSync state.

2023-04-20 12:49 UTC, RafalKorepta requested changes
Forgot to ask. Can you bump the chart version https://github.com/redpanda-data/helm-charts/blob/98b10ae0cced0c9a8be4f56750b94dc6ec88e9a1/charts/console/Chart.yaml#L30 ?

2023-04-20 18:10 UTC, stefan-caraiman commented
> Forgot to ask. Can you bump the chart version
> 
> https://github.com/redpanda-data/helm-charts/blob/98b10ae0cced0c9a8be4f56750b94dc6ec88e9a1/charts/console/Chart.yaml#L30
> 
> ?

done ✅

2023-04-21 13:37 UTC, RafalKorepta approved these changes

2023-04-21 14:19 UTC, RafalKorepta approved these changes

2023-04-25 23:30 UTC, joejulian approved these changes
We've talked about this internally a bit. Having a plain-text secret in the values.yaml isn't ideal, but the helm release will reside in a Secret and the template places the data in a Secret so it's not completely horrible. Plus, the rest of this chart has this same problem so I'll give my approval as well.

Sorry this required some patience.

2023-05-08 17:46 UTC, joejulian commented
rebased and bumped chart version

2023-05-08 17:47 UTC, merged