reserve memory auto configuration added #49
redpanda-data/helm-charts pull request #63
Opened 2022-05-19 16:34 UTC by redp01

Reserve memory can be auto configured. It utilises the formula supplied by @travisdowns . There is potentially scope to override these values directly in the config without the automatic configuration though hopefully we can discuss on this PR.

2022-05-19 20:15 UTC, travisdowns commented
cc @BenPope

2022-05-23 14:37 UTC, vuldin requested changes
Thanks for the PR @redp01 ! PR #50 was merged and introduced conflicts. After speaking with @RafalKorepta we agreed that merging both PRs would be the best approach: https://github.com/redpanda-data/helm-charts/pull/50#issuecomment-1134726911 . This will mean a minor change to this PR though to ensure that if specific memory values aren't given in the `values.yaml` then it defaults to the values this PR would provide. Let me know if you have any questions or concerns.

2022-07-18 21:34 UTC, vuldin commented
Hi @redp01, could this PR instead be pointing to v2 branch? We can discuss this at some point, but you likely already know the reason (that is the target for all next version changes).

2022-07-28 03:55 UTC, vuldin commented
Closing this since the changes were included and expanded upon in https://github.com/redpanda-data/helm-charts/pull/127

2022-07-28 03:55 UTC, closed without merging