HPA Bug fix with updated api version
redpanda-data/helm-charts pull request #926
Opened 2023-12-08 19:27 UTC by bhataprameya

HPA Bug fix with updated api version

2023-12-11 12:53 UTC, RafalKorepta approved these changes

2023-12-11 12:54 UTC, RafalKorepta requested changes
Please bump https://github.com/redpanda-data/helm-charts/blob/543b2485a014407fd1af1ff58ddc333685154d56/charts/console/Chart.yaml#L30 console chart version.

2023-12-11 21:30 UTC, bhataprameya commented
> Please bump
> 
> https://github.com/redpanda-data/helm-charts/blob/543b2485a014407fd1af1ff58ddc333685154d56/charts/console/Chart.yaml#L30
> 
> console chart version.

done

2023-12-12 07:23 UTC, RafalKorepta approved these changes

2023-12-12 07:23 UTC, merged